#!/bin/bash
echo "Running SonarLint validation script..."

# Path to the PowerShell script
powershell -ExecutionPolicy Bypass -File "$(git rev-parse --show-toplevel)/.git-hooks/validate-sonarlint.ps1"
